### ISSUE TITLE
Updating fails

### ISSUE THREAD

**Issue by Just-Insane** [mrlesmithjr/ansible-netdata#23]
Setting `netdata_update_force: true` or:
```
netdata_auto_updates:
  enabled: true
  day: "*"
  hour: 6
  minute: 0
  user: root
  weekday: "*"
```

Seems to fail silently. The update section passes, however netdata is not updated, and prompts for an update in the UI, even after restarting the netdata service.

Additionally, it does not appear that the netdata-updater.sh script is created in the `/usr/local/src/netdata` folder. (It is not clear if `netdata_updater: ./netdata-updater.sh` needs to be defined in order to have the script created).

I have resorted to clearing out the /usr/local/src/netdata folder and then running this role to re-install netdata (which still does not get the latest version).
