### ISSUE TITLE
Error in usage of health alarm notify configs in defaults/main.yml

### ISSUE THREAD

**Issue by jdelvecchio** [mrlesmithjr/ansible-netdata#28]
Hi,

In defaults/main.yml there is a small error
```yml
# Define configuration for health_alarm_notify.conf.
# Example:
# netdata_health_alarm_notify_configs:
#   https_proxy: http://localhost:3128
#   SLACK_WEBHOOK_URL: https://hooks.slack.com/...
netdata_alarm_notify_configs: {}
```

Should be 
```yml
# Define configuration for health_alarm_notify.conf.
# Example:
# netdata_health_alarm_notify_configs:
#   https_proxy: http://localhost:3128
#   SLACK_WEBHOOK_URL: https://hooks.slack.com/...
netdata_health_alarm_notify_configs: {}
```

Added _health_

Thanks for the role, works great.

**Comment by jdelvecchio** [comment]
Little update on the issue, I can't seem to make this variable work.
I've tried adding a SLACK_WEBHOOK_URL, here is my playbook :

```yml
roles:
    - role: netdata
      netdata_bind_to:
        - "127.0.0.1"
      netdata_alarm_configure: true
      netdata_health_alarm_notify_configs:
        SLACK_WEBHOOK_URL: "https://hooks.slack.com/blabla"

```

When executed, it goes fine, but the file /etc/netdata/health_alarm_notify.conf is looking like this :
```
# BEGIN ANSIBLE MANAGED BLOCK

# END ANSIBLE MANAGED BLOCK
```

Have I done something wrong in the definition of my variables ?
Thanks a lot

**Comment by xciter327** [comment]
I have the same problem. I'm not using quotation marks for the key tough.

**Comment by xciter327** [comment]
Actually it's without "health".

**Comment by mrlesmithjr** [comment]
Has this issue still been experienced? If it has we can work towards getting this resolved. Otherwise, can we close this?

**Comment by uqperryk** [comment]
Just if anyone else runs across this, the following works for me:
```
    netdata_alarm_configure: true
    netdata_alarm_notify_configs:
      SEND_SLACK: "YES"
      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/XXXXXXXXX/YYYYYYYYYY/ZZZZZZZZZZZZZZZZZZZZ
      DEFAULT_RECIPIENT_SLACK: your_slack_channel_name
```

Without the quotes around YES, it assumes a boolean and enters text of "True" into the config file and Slack notifications do not work.

p.s Thanks for the playbooks, good stuff.
