### ISSUE TITLE
Uninstall functionality problems

### ISSUE THREAD

**Issue by utelisysadmin** [mrlesmithjr/ansible-netdata#30]
First, I would like to thank You for making this role public. It was very handy for me.

Using it on nodes which had Netdata pre-installed before however proved to be problematic for me. The uninstall functionality does not work correctly as it relies on the uninstall script to be in a specific directory. I've so far found it in 3 different other directories which are not the root Netdata directories.

The simplest fix I can think of was to add two extra task to the uninstall section to download the uninstall script from Netdata and set the .environment file so it can run.

Something along the lines of:

```
- name: uninstall | Download uninstaller
  get_url:
    url: https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/netdata-uninstaller.sh
    dest: /usr/local/src/netdata/netdata-uninstaller.sh
    mode: u+rwx

- name: uninstall | Create .environment file
  copy:
    dest: "/etc/netdata/.environment"
    content: |
      NETDATA_PREFIX=""
      NETDATA_ADDED_TO_GROUPS=""
```

proved sufficient for my use case. Maybe a conditional check to see if a .environment file exists would be handy for other people that have customized the installation.
